### POST request to Register a new Patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Aadarsh Pandey with Billing Account",
  "email": "biller@test.com",
  "address": "Billing Layout, Bengaluru",
  "dateOfBirth": "2006-09-13",
  "registeredDate": "2025-03-25"
}

###