### Login Request to retrieve a Token
POST http://lb-e49390a4.elb.localhost.localstack.cloud:4004/auth/login
Content-Type: application/json

{
  "email": "testing@test.com",
  "password": "password123"
}

> {% client.global.set("token",response.body.token) %}

###