name: Build and Upload JAR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: clynic-service-jar
          path: target/*.jar
