name: Build and Release JAR

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven - Clynic-Service
        run: mvn clean package --file Clynic-Service/pom.xml

      - name: Build with Maven - Billing-Service
        run: mvn clean package --file Billing-Service/pom.xml

      - name: Build with Maven - Analytics Service
        run: mvn clean package --file Analytics-Service/pom.xml

      - name: Build with Maven - API Gateway
        run: mvn clean package --file clynic-api-gateway/pom.xml

      - name: Build with Maven - Clynic Auth Service
        run: mvn clean package --file Clynic-Auth-Service/pom.xml

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Clynic-Service/target/*.jar,Billing-Service/target/*.jar,Analytics-Service/target/*.jar,clynic-api-gateway/target/*.jar,Clynic-Auth-Service/target/*.jar"
          tag: "v1.0.${{ github.run_number }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "Release v1.0.${{ github.run_number }}"
          body: "Automated release of JAR file."

      - name: Delete Old Releases
        uses: Nats-ji/delete-old-releases@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep-count: '3'
          remove-tags: true
          keep-old-minor-releases: false