name: Build and Release JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven - Clynic-Service
        run: mvn clean package --file Clynic-Service/pom.xml

      - name: Build with Maven - Billing-Service
        run: mvn clean package --file Billing-Service/pom.xml

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Clynic-Service/target/*.jar,Billing-Service/target/*.jar"
          tag: "v1.0.${{ github.run_number }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "Release v1.0.${{ github.run_number }}"
          body: "Automated release of JAR file."
