name: Build and Release JAR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package --file Clynic-Service/pom.xml

      - name: Create Version Tag
        id: tag
        run: |
          VERSION=$(date +'%Y%m%d-%H%M%S')  # Generate a timestamp-based version
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git tag -a "v$VERSION" -m "Release version $VERSION"
          git push origin "v$VERSION"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          files: Clynic-Service/target/*.jar
          body: "Automated release of JAR file."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
